### ISSUE TITLE
Auto Update Magitek

### ISSUE THREAD

**Issue by X015** [Zimgineering/repoBuddy#15]
Hallo,

i have a Problem with repoBuddy it always thinks there is a Update available for Magitek und try's to update it but insted it delete the files from the Magitek Folder.

tyvm!

**Comment by Zimgineering** [comment]
That's a weird one, did you add Magitek to the repo list? Magitek has its own updater, and repoBuddy just adds a convenient direct download link but doesn't manage the updates.

**Comment by X015** [comment]
No i didn't
Here is the Log:

```
[14:18:20.242 N] [Auto-Updater][Magitek] Updating to Version: 52
.
[14:18:20.554 N] [Auto-Updater][Magitek] System.ArgumentException: 1 is not a supported code page.
Parameter name: codepage
   at System.Text.Encoding.GetEncoding(Int32 codepage)
   at ICSharpCode.SharpZipLib.Zip.ZipFile.ReadEntries()
   at ICSharpCode.SharpZipLib.Zip.ZipFile..ctor(Stream stream)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner)
   at MagitekLoader.CombatRoutineLoader.Extract(Byte[] files, String directory) in C:\Users\USER\Desktop\RB\Routines\Magitek\MagitekLoader.cs:line 454
[14:18:20.554 N] [Auto-Updater][Magitek] [Error] Could not extract new files.
```
As you can see repoBuddy try's to update it to version 52 but the current version is 751

**Comment by Zimgineering** [comment]
That is Magitek's updater, and that error generally follows some Localization issue. You can try setting your system language to en-US.

If that doesn't work then you can try downloading the [most recent version](https://cdn.discordapp.com/attachments/332630645849325568/989323185654743060/Magitek.zip) directly and post about the error in the Magitek discord along with your system locale to help them fix it.

**Comment by X015** [comment]
> That is Magitek's updater, and that error generally follows some Localization issue. You can try setting your system language to en-US.
> 
> If that doesn't work then you can try downloading the [most recent version](https://cdn.discordapp.com/attachments/332630645849325568/989323185654743060/Magitek.zip) directly and post about the error in the Magitek discord along with your system locale to help them fix it.

The tip with the System Language did it!
My first Language was set to 1. English (Austria) and 2. English (United States) changed them up to

1. English (United States)
2. English (Austria)

and everything works fine.

tyvm!
